name: "Vibie"
description: "Tutorial Pemrograman Visual Basic .Net Bahasa Indonesia"

author: "irfnrdh"

url: "http://vibie.web.id/"
baseurl: ""

author-bio: "Part time artist, full time creator"


twitter: irfnrdh
github: irfnrdh
dribbble: irfnrdh
instagram: irfnrdh


ga_domain: vibie.web.id
ga_tracking_id: 


markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"


sass:
  sass_dir: _scss
  style: :compressed
